name: Dependabot auto merge

# Check Dependabot PRs every weekday at 06:30 UTC (after Dependabot)
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * 1-5"

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - name: Dependabot auto approve
        uses: PabioHQ/dependabot-pr-action@v1.1.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-label: true
          approve: true
          merge: false

      - name: Dependabot auto merge
        uses: akheron/dependabot-cron-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
