name: Dependabot auto merge

on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot auto merge
        uses: akheron/dependabot-cron-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
