name: Dependabot auto merge

on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    if: github.actor == "dependabot[bot]"
    steps:
      - name: Dependabot auto merge
        uses: KeisukeYamashita/auto-dependabot-pull-request-merge@v1
        with:
          strategy: squash
